# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Backup data
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/fly-backups.yml"
  schedule:
    - cron: "0 2 * * *"

jobs:
  backup:
    name: Backup data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Get machine ID
        id: machine
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          echo "id=$(flyctl machines list --app "${{ secrets.FLY_APP_NAME }}" --json | jq -r '.[0].id')" >> $GITHUB_OUTPUT
      - name: Start machine
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl machine start --app "${{ secrets.FLY_APP_NAME }}" "${{ steps.machine.outputs.id }}"
      - name: Get backup data
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl ssh sftp get --app "${{ secrets.FLY_APP_NAME }}" /app/data ./data --recursive
      - name: Install rclone
        run: |
          sudo apt-get install rclone
      - name: Upload to B2
        env:
          RCLONE_B2_ACCOUNT: "${{ secrets.B2_ACCOUNT_ID }}"
          RCLONE_B2_KEY: "${{ secrets.B2_ACCOUNT_KEY }}"
        run: |
          rclone sync ./data "b2:${{ secrets.B2_BUCKET_NAME }}/auth/"
