# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/fly-backups.yml"
  schedule:
    - cron: "0 2 * * *"

jobs:
  backup:
    name: Backup data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Get data
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl machine start --app "${{ secrets.FLY_APP_NAME }}"
          flyctl ssh sftp get --app "${{ secrets.FLY_APP_NAME }}" /data ./data --recursive
      - name: Upload to B2
        run: |
          rclone config create b2remote b2 account=${B2_ACCOUNT_ID} key=${B2_ACCOUNT_KEY}
          rclone sync ./data b2remote:${B2_BUCKET}/${BACKUP_PATH}/ --fast-list --transfers 8 --checkers 8
