# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "fly.toml"
      - ".github/workflows/fly-deploy.yml"
      - "scripts/**"
      - "services/**"
jobs:
  fly-config-validate:
    name: Validate Fly.io config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Validate config
        run: flyctl config validate  --app ${{ secrets.FLY_APP_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  dockerfile-lint:
    name: Run Hadolint on Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check Docker files with Hadolint
        uses: essentialkaos/hadolint-action@v1
        with:
          files: Dockerfile
          format: tty
          strict-labels: true
          failure-threshold: warning
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs:
      - fly-config-validate
      - dockerfile-lint
    concurrency: fly-deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v5
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy latest
        run: flyctl deploy --remote-only --config fly.toml --app ${{ secrets.FLY_APP_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
